# Render Configuration for SabaStudio Frontend

services:
  - type: web
    name: sabastudio-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://sabastudio-backend.onrender.com/api/v1
      - key: VITE_APP_NAME
        value: SabaStudio
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_APP_TITLE
        value: SabaStudio - Architecture & Design
      - key: VITE_NODE_ENV
        value: production
