# Railway Deployment Configuration
version: 1

services:
  frontend:
    build:
      dockerfile: docker/Dockerfile.client
      context: client/
    environment:
      VITE_API_URL: https://api-${{RAILWAY_PUBLIC_DOMAIN}}
    domains:
      - ${{RAILWAY_PUBLIC_DOMAIN}}

  backend:
    build:
      dockerfile: docker/Dockerfile.server
      context: server/
    environment:
      NODE_ENV: production
      PORT: 3001
      # MongoDB Atlas connection string
      MONGODB_URI: ${{MONGODB_ATLAS_URI}}
      JWT_SECRET: ${{JWT_SECRET}}
      CORS_ORIGIN: https://${{RAILWAY_PUBLIC_DOMAIN}}
      SMTP_HOST: ${{SMTP_HOST}}
      SMTP_PORT: ${{SMTP_PORT}}
      SMTP_USER: ${{SMTP_USER}}
      SMTP_PASS: ${{SMTP_PASS}}
      FROM_EMAIL: ${{FROM_EMAIL}}
      ADMIN_EMAIL: ${{ADMIN_EMAIL}}
      EMAIL_ENABLED: true
    domains:
      - api-${{RAILWAY_PUBLIC_DOMAIN}}

# Note: Using MongoDB Atlas (cloud-managed database)
# Set MONGODB_ATLAS_URI in Railway environment variables
# Your URI: mongodb+srv://nahidnajafih:W1GzR8rdjkCKHiPf@cluster0.4xzpb3q.mongodb.net/SabaStudio?retryWrites=true&w=majority&appName=Cluster0
